version: "3.4"
services:
  dd:
    image: ncrmro/docker-buildx:20.10.6-0.5.1
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    command: >
      docker buildx version
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    build:
      context: .
