version: "3.4"
services:
  dd:
    image: ncrmro/docker-buildx:19.03.10
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    command: >
      docker buildx version
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    build:
      context: .
